# Discord Bot Configuration
token = "MTQwNDYxMDgwOTczNjQ2MjMzNg.G6EZLE.mHNbAXEITfpTiO7uKAp5Ou0EsMQD7XRD9izfxI"
clientId = "1404610809736462336"
guildId = "1404266808143515749"

# Permissions and Channels
ownerRoleId = "1404271440621993984"
vouchInAllChannels = false
allowVouchChannelId = "1404278846152380598"
reviewChannelId = "1404278846152380598"
# Bot Settings
emojiVouch = "⭐"
businessName = "THC-STORE"
useThumbnailCustom = "https://i.ibb.co/QjNXHQ22/9z-Utf7-J-1.png"

# Embed Settings - Color Options
embedColor = 0
# Color examples (decimal format):
# 0 = Black
# 16777215 = White  
# 16711680 = Red
# 65280 = Green
# 39423 = Blue
# 16734003 = Orange
# 10181046 = Purple
# 15844367 = Yellow
# 3447003 = Discord Blues
# 15105570 = Gold

# Web Interface Settings
useWeb = false
webPort = 3000
webHost = "0.0.0.0"  # Use "0.0.0.0" for VPS access, "localhost" for local only

# Example configurations for different setups:

# Local development only:
# webHost = "localhost"
# webPort = 3000

# VPS/Server deployment:
# webHost = "0.0.0.0"
# webPort = 3000

# Custom port (if 3000 is taken):
# webPort = 8080

# Disable web interface:
# useWeb = false




